### ISSUE TITLE
ruvIII.nb could not run

### ISSUE THREAD

**Issue by gerrardmai** [limfuxing/ruvIIInb#3]
same parameter setting  for fastruvIII.nb & ruvIII.nb. 

only fastruvIII.nb could get the result.

is that the same effect when I set pCells.touse = 1 in fastruvIII.nb instead  ruvIII.nb?

**Comment by limfuxing** [comment]
Hi,
The original ruvIII.nb function does not use DelayedArray object so it's more memory-greedy and on occasions this poor memory management has resulted in the function taking forever to finish. We plan to deprecate ruvIII.nb in our major upgrade (expected in early Jan) with better memory management and automatic generation of M matrix inside the function. If you could wait a bit, I suggest you wait for the major upgrade. Otherwise, using fastruvIII.nb with pCells.touse=1 would give you very similar output to ruvIII.nb as you correctly deduced.
