### ISSUE TITLE
Control Genes are Often Mostly Zero Counts

### ISSUE THREAD

**Issue by DarioS** [limfuxing/ruvIIInb#5]
I am using the vignette example after successfully installing an unpacked Zip fle of the package.

```r
> sce
  class: SingleCellExperiment 
dim: 20352 6382
> length(ctl)
  1085
```
Many of the genes which should be stably expressed are **not** detected in the majority of cells.
```r
mediansControls <- apply(assay(sce)[intersect(ctl, rownames(assay(sce))), ], 1, function(geneRow) median(geneRow))
> summary(mediansControls)
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
 0.0000  0.0000  0.0000  0.7815  0.0000 73.0000
```
Why are genes which have mostly zero read counts used as stably expressed genes?

**Comment by limfuxing** [comment]
Hi Dario, we took all stably-expressed genes from this paper (https://academic.oup.com/gigascience/article/8/9/giz106/5570567) as negative controls. But for a specific dataset and when the overall seq depth is low such as for 10X data, even stably-expressed genes can have low expressions. It's important to note that our approach will look reasonably as long as there are a number of genes that are highly-expressed among the controls. But it's also possible that you have encountered an error because the built-in vignette is out of date. Could you try the updated vignette? Thanks

**Comment by DarioS** [comment]
Robust to control gene misspecification.
