### ISSUE TITLE
Unused Argument Strata and foreach Error

### ISSUE THREAD

**Issue by DarioS** [limfuxing/ruvIIInb#6]
The example code fails immediately with an unused argument error.

```r
#RUV-III-NB code
ruv3nb_out<-ruvIII.nb(Y=as.matrix(assays(sce)$counts), # count matrix with genes as rows and cells as columns
                    M=M, #Replicate matrix constructed as above
                    ctl=rowData(sce)$ctlLogical, #A vector denoting control genes
                    k=2, # dimension of unwanted variation factors
                    strata=sce$cluster_init)
```

> ```
> Error in ruvIII.nb:
>   unused argument (strata = sce$cluster_init)
> ```

If I remove `strata` parameter, it runs for a few minutes and then another error.

```r
"5430genes with all zero counts are removed following a Winsorization step."
"Batch variable not supplied...assuming cells come from one batch"
Error in value[[3L]](cond) : 
  'DoparParam()' foreach() error occurred: error writing to connection
```
Please provide working examples for users to try.

**Comment by limfuxing** [comment]
Hi Dario, the vignette in the package is out of date. You can find the latest vignette here https://bookdown.org/a2delivera/scRNAseq/. The link is also provided on the GitHub page. We are now advising users to use the fast version due to better memory handling. The error with foreach that you encountered can sometimes occur because of memory issues.

**Comment by DarioS** [comment]
Latest vignette's code runs without error.
